# Generated by Django 3.2.6 on 2021-08-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='active_sea',
            new_name='main_activity_territorial_data',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='ship',
            new_name='ship_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tonnage',
            new_name='ship_weight',
        ),
        migrations.AddField(
            model_name='profile',
            name='ship_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='user',
        ),
    ]
