# Generated by Django 3.2.6 on 2021-08-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('trench_num', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'trench',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mlResult',
            fields=[
                ('trench_num', models.IntegerField(primary_key=True, serialize=False)),
                ('loss', models.FloatField()),
                ('acc', models.FloatField()),
            ],
            options={
                'db_table': 'ml_result',
            },
        ),
    ]
