<<<<<<< HEAD
# Generated by Django 3.2.6 on 2021-08-21 20:22
=======
# Generated by Django 3.2.6 on 2021-08-20 17:23
>>>>>>> 357cc9a85f1f9b3c9f2cb1ccab8d70f828eed2b9

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('trench_num', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'trench',
                'managed': False,
            },
        ),
    ]
