# Generated by Django 3.2.6 on 2021-08-08 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trench',
        ),
    ]
