# Generated by Django 3.2.6 on 2021-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grid', '0004_delete_trench'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trench',
            fields=[
                ('trench_num', models.IntegerField(primary_key=True, serialize=False)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
            options={
                'db_table': 'trench',
                'managed': False,
            },
        ),
    ]
